---

- name: Run file commands
  hosts: all
  gather_facts: false

  tasks:
    - name: Create a directory
      file:
        path: /home/abaltazar/myfolder
        state: directory
        owner: abaltazar
        group: abaltazar

    - name: Delete sample-template.bak file
      file:
        path: /home/abaltazar/sample-template.bak
        state: absent
